version: 2.1

jobs:
  my_job:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: check
          command: |
            echo "This is triggered from changes in branch: ${CIRCLE_BRANCH}"

workflows:
  my_workflow:
    jobs:
      - my_job:
          filters:
            branches:
              only:
                - /nw-.*/
                - main
